### ISSUE TITLE
More information about this project

### ISSUE THREAD

**Issue by jacopo-j** [hatwheels/pos_ingenico_220_250_snake#1]
Hello. I was hoping you can answer some questions I got regarding to this project, which I found quite interesting: 

- supposing I want to do something similar to what you did, is the Ingenico SDK needed to develop apps for POS terminals available without particular restrictions? Do you know how it can be obtained?

- is it possible to flash a "mockup" firmware to a normal production POS in order to load and execute unsigned applications? 

- do you have any resource/documentation about how you did this besides the actual development of the application?

Thank you.

**Comment by hatwheels** [comment]
Hello. It makes me happy that someone finds it interesting. I did it in my free time while working for a FinTech multinational, they had a branch dedicated to POS development.

Concerning your questions:

-  The Ingenico POS come installed with all the Ingenico libraries. In order to be able to develop, a certain procedure has to be followed to make it a mockup. I don't remember how it goes and I never actually did it myself. On the other hand Ingenico POS are so far I know ARM-based so C libraries for ARM μC should theoretically. I would suggest contacting Ingenico directly through email and phone.

- It is possible to flash the development (mockup) POS to a production. As far as I remember there was a procedure involving installing a certification key proving it's a legit Ingenico POS. Again, I never did it myself. Customer support did it.

- You mean documentation of the SDK? The documentation should be available online for POS 220/250. I wrote it inside the POS application, which is proprietary and belongs to the FinTech multinational I mentioned. Clarify what you need exactly and I'll be glad to help.

If you want  I can contact some former colleagues for information.

**Comment by jacopo-j** [comment]
Thank you for your reply. As far as I can see then contacting Ingenico is a must in order to be able to do any of this.

This is a bit unfortunate because I do not work for any company involved in POS development, and I don't think Ingenico will care about a random developer wanting to mess around just for fun with some terminals found on eBay for 10$ :P

That was expected, tho. I guess I'll have to wait for another occasion. Thank you anyway

**Comment by hatwheels** [comment]
Let me ask my former colleagues and I'll come back at you.

**Comment by hatwheels** [comment]
Here's the answer from my colleagues.

For the SDK you need access from Ingenico. This means paying and attending a training session.
You can 'convert' a production POS to a mock-up with a certain image. The other way around though is not possible (once a mock-up, always a mock-up)...

**Comment by jacopo-j** [comment]
Okay, that was to be expected. Thank you again anyway
